repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
    -   id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures files end with a newline.
        entry: end-of-file-fixer
        language: python
        types: [text]
    -   id: mixed-line-ending
        name: Fix Mixed Line Endings
        description: Replaces mixed line endings with the native ones.
        entry: mixed-line-ending
        language: python
        types: [text]
        args: [--fix=lf]  # Use LF line endings for all files
    -   id: check-yaml
        name: Check YAML syntax
        description: Checks yaml files for parseable syntax.
        entry: check-yaml
        language: python
        types: [yaml]
    -   id: check-json
        name: Check JSON syntax
        description: Checks json files for parseable syntax.
        entry: check-json
        language: python
        types: [json]
    -   id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for files that contain merge conflict strings.
        entry: check-merge-conflict
        language: python
        types: [text]
    -   id: check-case-conflict
        name: Check for case conflicts
        description: Check for files with names that would conflict on a case-insensitive filesystem.
        entry: check-case-conflict
        language: python
